---
title: '1'
author: "Lambridge"
date: "2021/12/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(tmap)
library(geojsonio)
library(plotly)
library(rgdal)
library(broom)
library(mapview)
library(crosstalk)
library(sf)
library(sp)
library(spdep)
library(car)
library(fs)
library(janitor)
```

```{r}
SanFranciscoBoroughs <- st_read(here::here("data","geo_export_d80a3dd3-412b-48e6-ad9c-c5c6349fcbbf.shp"))
```

```{r}
tmap_mode("view")
qtm(SanFranciscoBoroughs)
```

```{r}
SanFranciscoBoroughs <- SanFranciscoBoroughs %>% 
  filter(aland10 != 419323)
```

```{r}
qtm(SanFranciscoBoroughs)
```

```{r}
print(SanFranciscoBoroughs)
```

```{r}
shape <- SanFranciscoBoroughs %>%
    st_transform(., crs=7131)
```

```{r}
qtm(shape)
```

```{r}
Graffiti<- read.csv(here::here("data","Graffiti.csv"), 
                         header = TRUE, sep = ",",  
                         encoding = "latin1",
                    ) %>% 
  na.omit()
```

```{r}
graffiti2<-Graffiti%>%
  separate(., Point, c("A", "B"), sep = ",")
  
graffiti2$A<-parse_number(graffiti2$A) ## leading $ and grouping character , ignored删除数据之前的非
graffiti2$B<-parse_number(graffiti2$B) ## leading $ and grouping character , ignored

graffiti3<- graffiti2%>%
  filter(A !=	0 )%>%
  filter(B != 0)%>%
  st_as_sf(., coords = c("B", "A"), 
                   crs = 4326)

graffiti4<- graffiti3%>%
filter(str_detect(Closed, "2019"))%>%
  #filter(str_detect(`Request Type`, "Building"))%>%
  st_transform(., crs=7131)
```

```{r}
graffiti_within <- graffiti4[shape, ,op=st_intersects]

tm_shape(shape) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(graffiti4) +
  tm_dots(col = "blue")
```

```{r}
Joinfun <- function(data1, data2){

output<- data1%>%
  st_join(Londonborough,.)%>%
  add_count(GSS_CODE, name="hotels_in_borough") 

  return(output)
}
```

```{r}

  points_sf_joined <- shape%>%
    st_join(graffiti4)%>%
    add_count(geoid10)%>%
    janitor::clean_names()%>%
    #calculate area
    mutate(area=st_area(.))%>%
    #then density of the points per ward
    mutate(density=n/area)%>%
    dplyr::select(geoid10 , neighborhood, density,n)%>%
    group_by(geoid10) %>%         
  summarise(geoid10 = first(geoid10),
          neighborhood= first(neighborhood),
          density= first(density),
          number=first(n))
```

```{r}
tmap_mode("view")
tm <- tm_shape(points_sf_joined) + 
  tm_polygons("density", 
              palette="PuBu")
tm
```

```{r}
breaks1<-c(0,5,100,400,1000,2000,3000,5000)
tmap_mode("view")
tm <- tm_shape(points_sf_joined) + 
  tm_polygons("number",
              breaks=breaks1,
              palette="PuBu")
tm
```

# OLS

```{r}
census_education <- read_csv(here::here("data","ACSST5Y2019.S1501_data_with_overlays_2021-12-08T045521.csv"),skip=1,
                             na = c("", "NA", "n/a"),
                             col_names = TRUE)
```

```{r}
census_education2 <- census_education %>% 
  clean_names()
```

```{r}
census_education3 <- shape %>%
  mutate(joiner = paste("1400000US", geoid10, sep=""))
```

```{r}
census_education4 <- census_education3 %>%
    left_join(.,
            census_education2, 
            by = c("joiner" = "id"))
```

```{r}
tmap_mode("plot")
qtm(census_education4, 
    fill = "estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate", 
    borders = NULL,  
    fill.palette = "Blues")
```

```{r}
desity <- st_drop_geometry(points_sf_joined) %>% 
  dplyr::select('density','geoid10','number')
census_education5 <- census_education4 %>%
    left_join(.,
            desity, 
            by = c("geoid10" = "geoid10"))
```

``` {census_education5$num}
```

```{r}
census_education5 <- st_drop_geometry(census_education5)
```

```{r}
census_education5 <- census_education5 %>% 
  as_tibble()
```

```{r}
Datatypelist <- census_education5 %>% 
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to="All_variables", 
               values_to="Variable_class")

Datatypelist
```

```{r}
Datatypelist <- census_education5 %>% 
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to="All_variables", 
               values_to="Variable_class")

Datatypelist
```

```{r}
census_education5$density<-as.numeric(census_education5$density)
```

```{r}
library(spatstat)
q <- qplot(x = `estimate_total_age_by_educational_attainment_population_18_to_24_years`, 
           y = `density`, 
           data=census_education5)
#plot with a regression line - note, I've added some jitter here as the x-scale is rounded
q + stat_smooth(method="lm", se=FALSE, size=1) + 
  geom_jitter()

```

```{r}
library(spatstat)
q <- qplot(x = `estimate_total_age_by_educational_attainment_population_18_to_24_years`, 
           y = `number`, 
           data=census_education5)
#plot with a regression line - note, I've added some jitter here as the x-scale is rounded
q + stat_smooth(method="lm", se=FALSE, size=1) + 
  geom_jitter()
```

```{r}
#run the linear regression model and store its outputs in an object called model1
Regressiondata<- census_education5%>%
  clean_names()%>%
  dplyr::select(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate,density)

#now model
model1 <- Regressiondata %>%
  lm(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate ~density,
     data=.)
```

```{r}
#run the linear regression model and store its outputs in an object called model1
Regressiondata<- census_education5%>%
  clean_names()%>%
  dplyr::select(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate,number)

#now model
model2 <- Regressiondata %>%
  lm(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate ~number,
     data=.)
```

```{r}
summary(model1)
```

```{r}
summary(model2)
```

```{r}
library(broom)
tidy(model1)
```

```{r}
glance(model1)

```

```{r}
library(tidypredict)
Regressiondata %>%
  tidypredict_to_column(model1)
```

### Assumptions Underpinning Linear Regression

```{r}
# use Janitor to clean up the names.

census_education5 <- census_education5 %>%
  clean_names()

#let's check the distribution of these variables first

ggplot(census_education5, aes(x=estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 5) + 
  geom_density(colour="red", 
               size=1, 
               adjust=1)
```

```{r}
ggplot(census_education5, aes(x=density)) +
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1) + 
  geom_density(colour="red",
               size=1, 
               adjust=1)
```

```{r}
ggplot(census_education5, aes(x=)) +
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1) + 
  geom_density(colour="red",
               size=1, 
               adjust=1)
```

```{r}
ggplot(census_education5, aes(x=estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate)) + 
  geom_histogram()
```

```{r}
qplot(x = estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate, 
      y = number, 
      data=census_education5)
```

```{r}
ggplot(census_education5, aes(x=log(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate))) + 
  geom_histogram()
```

```{r}

```

```{r}
ggplot(census_education5, aes(x=log(estimate_total_age_by_educational_attainment_population_18_to_24_years))) + 
  geom_histogram()
```

```{r}
ggplot(census_education5, aes(x=log(number))) + 
  geom_histogram()
```

```{r}
symbox(~density, 
       census_education5, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```

```{r}
ggplot(census_education5, aes(x=(density)^0.5)) + 
  geom_histogram()
```

```{r}
qplot(x = log(estimate_total_age_by_educational_attainment_population_18_to_24_years_less_than_high_school_graduate), 
      y = log(density),
      data=census_education5)
```

```{r}
#save the residuals into your dataframe

model_data <- model2 %>%
  augment(., Regressiondata)

#plot residuals
model_data%>%
dplyr::select(.resid)%>%
  pull()%>%
  qplot()+ 
  geom_histogram()
```

```{r}
Regressiondata2<- census_education5%>%
  clean_names()%>%
  dplyr::select(density,estimate_total_age_by_educational_attainment_population_18_to_24_years,number,)

Regressiondata2 <- Regressiondata2 %>% 
  mutate(log_number=log(number)) %>% 
  mutate(log_pop=log(estimate_total_age_by_educational_attainment_population_18_to_24_years)) %>% 
  filter(log_pop!=-Inf)

model2 <- lm(density ~ log_pop+number, data = Regressiondata2)

#show the summary of those outputs
tidy(model2)
```

```{r}
summary(model2)
```

```{r}
glance(model2)
```

```{r}
#and for future use, write the residuals out
model_data2 <- model2 %>%
  augment(., Regressiondata2)
census_education5 <- census_education5 %>% 
  mutate(log_pop=log(estimate_total_age_by_educational_attainment_population_18_to_24_years)) %>% 
  filter(log_pop!=-Inf)
# also add them to the shapelayer
census_education5 <- census_education5 %>%
  mutate(model2resids = residuals(model2))
```

```{r}
residuals(model2)
```

```{r}
library(corrr)

Correlation <- census_education5 %>%
  dplyr::select(census_education5$density,estimate_total_age_by_educational_attainment_population_18_to_24_years,number) %>%correlate() %>%
  # just focus on GCSE and house prices
  focus(-density, mirror = TRUE) 


#visualise the correlation matrix
rplot(Correlation)

```

```{r}
Regressiondata2$estimate_total_age_by_educational_attainment_population_18_to_24_years
```

## vif

```{r}
position <- c(15:20)

Correlation_all<- census_education5 %>%
  dplyr::select(position)%>%
    correlate()
Correlation_all <- Correlation_all %>%
  na.omit()
  
rplot(Correlation_all)
```

```{r}
vif(model2)
```

```{r}
#print some model diagnositcs. 
par(mfrow=c(2,2))    #plot to 2 by 2 array
plot(model2)
```

```{r}
#run durbin-watson test
DW <- durbinWatsonTest(model2)
tidy(DW)
```

```{r}
#now plot the residuals
tmap_mode("view")
#qtm(LonWardProfiles, fill = "model1_resids")
census_education5 = st_as_sf(census_education5)
tm_shape(census_education5) +
  tm_polygons("model2resids") +
tm_shape(points_sf_joined) + tm_dots(col = "density")
```

```{r}
#calculate the centroids of all Wards in London
coordsW <- census_education5%>%
  st_centroid()%>%
  st_geometry()

plot(coordsW)
```

```{r}
#Now we need to generate a spatial weights matrix 
#(remember from the lecture a couple of weeks ago). 
#We'll start with a simple binary matrix of queen's case neighbours

LWard_nb <- census_education5 %>%
  poly2nb(., queen=T)

#or nearest neighbours
knn_wards <-coordsW %>%
  knearneigh(., k=4)

LWard_knn <- knn_wards %>%
  knn2nb()

#plot them
plot(LWard_nb, st_geometry(coordsW), col="red")
```

```{r}
plot(LWard_knn, st_geometry(coordsW), col="blue")

```

```{r}
#create a spatial weights matrix object from these weights

Lward.queens_weight <- LWard_nb %>%
  nb2listw(., style="W")

Lward.knn_4_weight <- LWard_knn %>%
  nb2listw(., style="W")
```

```{r}
Queen <- census_education5 %>%
  st_drop_geometry()%>%
  dplyr::select(model2resids)%>%
  pull()%>%
  moran.test(., Lward.queens_weight)%>%
  tidy()
```

```{r}
Nearest_neighbour <- census_education5 %>%
  st_drop_geometry()%>%
  dplyr::select(model2resids)%>%
  pull()%>%
  moran.test(., Lward.knn_4_weight)%>%
  tidy()

Queen
```

```{r}
Nearest_neighbour
```
1+1